// Generated by CoffeeScript 1.6.3
(function() {
  window.Todos = Ember.Application.create({
    name: 'EmberJS with coffee'
  });

  Todos.ApplicationAdapter = DS.FixtureAdapter.extend();

}).call(this);
