// Generated by CoffeeScript 1.6.3
(function() {
  Todos.TodoController = Ember.ObjectController.extend({
    actions: {
      deleteTodo: function() {
        var todo;
        todo = this.get('model');
        todo.deleteRecord();
        return todo.save();
      }
    }
  });

}).call(this);
